---

- hosts: all

  vars:
<<<<<<< Updated upstream
    - node_js_version: 8.9.0
=======
    - node_js_version: 10.15.3
>>>>>>> Stashed changes
 
  tasks:  
  - import_tasks: ansible-task-disable-sudo-timeout.yml
  - import_tasks: ansible-task-install-nvm-node.yml
  - import_tasks: ansible-task-enable-sudo-timeout.yml